/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NgModule, ModuleWithProviders, SkipSelf, Optional } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ApiConfiguration, ApiConfigurationParams } from './api-configuration';

import { ApiMessageService } from './services/api-message.service';
import { ApiChatService } from './services/api-chat.service';
import { ApiUse4RService } from './services/api-use-4-r.service';

/**
 * Module that provides all services and configuration.
 */
@NgModule({
  imports: [],
  exports: [],
  declarations: [],
  providers: [
    ApiMessageService,
    ApiChatService,
    ApiUse4RService,
    ApiConfiguration
  ],
})
export class api.module.ts {
  static forRoot(params: ApiConfigurationParams): ModuleWithProviders<api.module.ts> {
    return {
      ngModule: api.module.ts,
      providers: [
        {
          provide: ApiConfiguration,
          useValue: params
        }
      ]
    }
  }

  constructor( 
    @Optional() @SkipSelf() parentModule: api.module.ts,
    @Optional() http: HttpClient
  ) {
    if (parentModule) {
      throw new Error('api.module.ts is already loaded. Import in your base AppModule only.');
    }
    if (!http) {
      throw new Error('You need to import the HttpClientModule in your AppModule! \n' +
      'See also https://github.com/angular/angular/issues/20575');
    }
  }
}
